
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import "MilitaryUnit.sol";
// This is class that describes you smart contract.
contract Archer is MilitaryUnit{
    
   constructor(address castle) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
     
        addressMilitaryBase = castle;
        setClass("Лучник");
        setDefense(1);
        setDescription("Могучий стрелок");
        setHp(5);
        setCurHp(5);
        setAttack(3);
    }
    function setAttackW(uint v) public{
        setAttack(v);
    }
    function setDefenseW(uint v) public{
        setDefense(v);
    }

    
}
